# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'NewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApp
  pod 'PagingTableView'
  pod 'ProgressHUD'
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'NewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
